### ISSUE TITLE
CommandException during /probending team create TeamOne

### ISSUE THREAD

**Issue by poma123** [ProjectKorra/Probending#49]
Here is it:
```
15.01 20:23:36 [Server] INFO poma123 issued server command: /probending team create TeamOne
15.01 20:23:36 [Server] ERROR null
15.01 20:23:36 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'probending' in plugin Probending v1.0.1
15.01 20:23:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:673) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
15.01 20:23:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
15.01 20:23:36 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.projectkorra.projectkorra.GeneralMethods.getBendingPlayer(Ljava/lang/String;)Lcom/projectkorra/projectkorra/BendingPlayer;
15.01 20:23:36 [Server] INFO at com.projectkorra.probending.Commands$1.onCommand(Commands.java:927) ~[?:?]
15.01 20:23:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1304]
15.01 20:23:36 [Server] INFO ... 15 more

**Comment by v-h-gn** [comment]
Probending is severely outdated, Id recommend not using it until its updated
